version: '3'
services:
   node-app:
    image: mahmoud899/najar:tagname
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - "4000:4000"
    environment:
    - DOCKER_DEFAULT_PLATFORM=linux/amd64
    - PORT=4000

